const Thread = require('..')
const thread = new Thread(() => {
  /([a-zA-Z1-9あ-んａ-ｎ]+)+$/.test('aaaaaaaaaaaaaaaaaaaaaaaaaaaa!')
})
thread.start()
thread.interruptIn(3000)
console.log('Expected: exit on 3 seconds')
thread.on('resolved', result => console.log('Resolved: ' + result))
thread.on('rejected', error => console.log('Rejected: ' + error))
thread.on('interrupt', () => console.log('Interrupted'))
